spring:
  application:
    name: event-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/eventflowx}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9090/realms/eventflowx/protocol/openid-connect/certs}

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eventflowx:
  security:
    enabled: ${EVENTFLOWX_SECURITY_ENABLED:true}
    expected-audience: ${EVENTFLOWX_EXPECTED_AUDIENCE:eventflowx-ui}
