spring:
  application:
    name: wallet-service

  profiles:
    active: dev   # default profile

server:
  port: 8084

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:walletdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: wallet_user
    password: wallet_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
